spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/hxg?useSSL=false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging.level.com.hxg: debug