spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mybatis?useSSL=false
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 50
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: select 1
      time-between-eviction-runs-millis: 60000
      filters: config,wall,stat
      connect-properties: config.decrypt=true;druid.stat.slowSqlMillis=200;druid.stat.logSlowSql=true;
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  #必须要
  http:
    encoding:
      force: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-conf.xml

#分页插件
pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql