spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mybatis?useSSL=false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  #必须要
  http:
    encoding:
      force: true
logging.level.com.hxg: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true